### ISSUE TITLE
liblz4.dll

### ISSUE THREAD

**Issue by Dzoiver** [myst6re/deling#20]
I couldn't launch a program because of error telling me liblz4.dll isn't found. Thought I need to install something and I couldn't find how and what, but I copied this file from earlier version and it worked. So i guess the file is missing?

**Comment by Sebanisu** [comment]
https://github.com/lz4/lz4/releases see if that library works. Might need the version that deling is compiled with.

**Comment by myst6re** [comment]
I updated the two last releases
