### ISSUE TITLE
I cant find the manual. 

### ISSUE THREAD

**Issue by TRiKixDYA** [myst6re/deling#30]
how do I import FF8 to edit it? THANKS so much

**Comment by myst6re** [comment]
Hello, you cannot "import FF8" as a whole. Deling can open and edit FS archives, find them in your FF8 PC installation directory in the /Data subdirectory.

For FF8 Remastered use a zzz extractor like this one: https://github.com/Sebanisu/zzzDeArchive/releases

Also this is not the place to ask for guidance, please go to the official Topic in the Qhimm forum here: https://forums.qhimm.com/index.php?topic=13050.msg181320#msg181320
