### ISSUE TITLE
Adding a directory with subfolders

### ISSUE THREAD

**Issue by bosshunter** [myst6re/deling#5]
If you try add a directory with subfolders, instead of adding the respecting subfolders, it creates a file entry with <subfolder_name>/<file_name>

Example: I tried to add a directory "mapdata" with the subfolders "bd", "bg", "gg", "gn" and "sd", but instead of adding the files to their respective directories, it resulted in what is seen below:

![image](https://user-images.githubusercontent.com/3970315/68992902-87229400-0869-11ea-9ac5-54dec8dddfbe.png)

**Comment by myst6re** [comment]
Ok, weird. I do not know when I could fix this, but noted.

**Comment by myst6re** [comment]
Fixed in upcoming release 0.10.1b
